version: '3.8'

services:
  web:
    image: liyaodev/my-gpt-reader:v1.0.0
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    ports:
      - ${PORT}:8080
    volumes:
      - .:/app

networks:
  default:
    name: gpt_reader
